[package]
name = "tex-2-spartan"
version = "0.1.0"
authors = ["sam <barrett370@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap={version="*", features=["yaml"]}
regex="*"
